spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost/mmintegration?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true"
    username: mmiuser
    password: mmipassword
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idleTimeout: 60000
      maxLifetime: 1800000
      jdbc4ConnectionTest: true
      minimumIdle: 0
      maximumPoolSize: 10

  datasourceGhost:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost/ghost?characterEncoding=UTF-8"
    username: root
    password: example
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idleTimeout: 60000
      maxLifetime: 1800000
      jdbc4ConnectionTest: true
      minimumIdle: 0
      maximumPoolSize: 5

  mvc:
    logResolvedException: false

  security:
    oauth2:
      client:
        registration:
          mattermost:
            clientId: hdouudoy53g6bddt1sqcp7es4y
            clientSecret: 17ojefizipn4pnbotk3rrir5ro
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          mattermost:
            authorizationUri: "http://localhost:8065/oauth/authorize"
            tokenUri: "http://localhost:8065/oauth/access_token"
            userInfoUri: "http://localhost:8065//api/v4/users/me"
            userNameAttribute: username

  thymeleaf:
    cache: false

logging:
  level:
    app: DEBUG
  pattern:
    console: "%-5p %d{HH:mm:ss.SSS} [%t] %c{0} - %m%n"

app:
  ghost:
    api:
      url: "http://localhost:2368"
      key: 676acb97cbf37a78794375697b
    outgoingWebhook:
      authorizedkey: r2vpgz6scd7kfv9rshs9w4s62x
  mattermost:
    api:
      url: "http://localhost:8065"
      accessToken: hqt7cbbfeib8ffguut8a6r93oe

---
spring:
  config:
    activate:
      on-profile: production
  thymeleaf:
    cache: true

logging:
  level:
    app: INFO
  pattern:
    console: "%-5p %d [%t] %c{0} - %m%n"
